# .streamlit/config.toml

[theme]
# Varsayılan tema "light" (açık) veya "dark" (koyu) olabilir.
# Kullanıcılar bunu uygulama menüsünden değiştirebilir.
base="dark"

# Uygulamanın ana vurgu rengi
primaryColor="#FF4B4B"

# Arka plan, ikincil arka plan ve metin renkleri
# (İsteğe bağlı, varsayılanlar genellikle yeterlidir)
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#262730"