# .streamlit/secrets_example.toml
# Bu dosya örnek olarak sunulmuştur. Gerçek secrets.toml dosyasını Streamlit Cloud'da yapılandırın.

# API-Football anahtarınızı buraya ekleyin
API_KEY = "your_api_football_key_here"

# Not: Bu dosya GitHub'a yüklenecek, gerçek API anahtarınızı buraya yazmayın!
# Streamlit Cloud'da secrets bölümünden API_KEY'i ekleyeceksiniz.